name: Generate Index

on:
  push:
    branches:
      - main

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Index
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html lang=\"en\" data-google-analytics-opt-out>" >> index.html
          echo "<head>" >> index.html
          echo "  <meta charset=\"UTF-8\">" >> index.html
          echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">" >> index.html
          echo "  <title>Index of Files</title>" >> index.html
          echo "</head>" >> index.html
          echo "<body>" >> index.html
          echo "  <h2>Index of Files</h2>" >> index.html
          echo "  <ul id=\"file-list\">" >> index.html
          for file in $(ls *.html | grep -v "index.html"); do
            echo "    <li><a href=\"https://leigh-code.github.io/Canvas/">$file</a></li>" >> index.html
          done
          echo "  </ul>" >> index.html
          echo "</body>" >> index.html
          echo "</html>" >> index.html

      - name: Commit Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add index.html
          git commit -m 'Automated index.html generation'
          git push
